tunnel: 346463bc-8eed-41ed-82fa-580252dd0e00
credentials-file: /root/.cloudflared/346463bc-8eed-41ed-82fa-580252dd0e00.json

ingress:
  # Existing Services
  - hostname: ssh.kawamonn.com
    service: ssh://localhost:22
  - hostname: ha.kawamonn.com
    service: http://localhost:8123

  # Kawamonn Platform Services
  - hostname: home.kawamonn.com
    service: http://localhost:5005
  - hostname: register.kawamonn.com
    service: http://localhost:5001
  - hostname: account.kawamonn.com
    service: http://localhost:5002
  - hostname: admin.kawamonn.com
    service: http://localhost:5003
  - hostname: web.kawamonn.com
    service: http://localhost:5004

  # Fallback
  - service: http_status:404
